spring:
  application:
    name: demo
  security:
    user:
      name: nijunyang
      password: 123456
server:
  compression:
    enabled: false
    mime-types: text/html,text/xml,text/plain,application/json,application/xml
    min-response-size: 1KB
demo:
  info: 是不是乱码
